version: '3'

services:
  db:
    container_name: db
    image: mongo:3.5.10
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  
  app:
    container_name: app
    image: node:17
    working_dir: /usr/app
    restart: always
    command: bash -c "yarn --production=true && yarn debug"
    volumes: 
      - ./dist/:/usr/app/dist/
      - ./package.json:/usr/app/package.json
    ports:
      - 3000:3000
      - 9222:9222
    links: 
      - db