version: '3'

services:
  db:
    container_name: db
    image: mongo:3.5.10
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - 27017:27017
  
  app:
    container_name: app
    build: .
    image: clean-node-api
    restart: always
    command: yarn start
    volumes: 
      - ./dist:/usr/app/dist
    ports:
      - 3000:3000
    links: 
      - db